services:
  postgres:
    image: docker.io/library/postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: "trustify"
      POSTGRES_DB: "trustify"
    restart: always
    shm_size: '1g'
