[package]
name = "huevos-common"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
#huevos-api = { path = "../api"}
anyhow = "1.0.72"
log = "0.4.19"
env_logger = "0.10.0"
serde_json = "1.0.104"
thiserror = "1"
serde = "1.0.183"
packageurl = "0.3.0"


[dev-dependencies]
